#!/bin/bash -l
#SBATCH -J circular                # Job name
#SBATCH -N 1                 # Total number of nodes (16 cores/node)
#SBATCH -n 1              # Total number of tasks
#SBATCH --qos=high
#SBATCH -p photons                  # Queue name
#SBATCH -o run_%j.log          # Name of stdout output file (%j expands to jobid)
#SBATCH -t 1-00:00:00            # Run time (hh:mm:ss)
#SBATCH --mem=8G
#SBATCH --exclude=photon13,photon11

bash
#conda activate obspy
#python TDSE.py

python /home/becker/spwa4419/Documents/Circular/TDSE.py

